package com.sbmInternProject.InsuranceAgency.Controllers;

import com.sbmInternProject.InsuranceAgency.Entities.User;
import com.sbmInternProject.InsuranceAgency.Repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
public class UserController {

    @Autowired // This means to get the bean called userRepository,Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @RequestMapping("/")
    public String hello() {
        return "Hello World!";
    }

   // @PostMapping(path="/add") // Map ONLY POST Requests
    @RequestMapping(
            value = "/add",
            produces = "application/json",
            method = {RequestMethod.POST})
    public @ResponseBody String addNewUser (@RequestParam String name,
                                            @RequestParam String email,
                                            @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User newUser = new User();
        newUser.setUserName(name);
        newUser.setEmail(email);
        newUser.setPassword(password);
        userRepository.save(newUser);
        return "Saved";
    }
    @GetMapping("/users")
    public List<User> getAllUsers(){
        return userRepository.findAll();
    }

}
